workspace(name = "test")

local_repository(
    name = "rules_oci_bootstrap",
    path = "../",
)

load("@rules_oci_bootstrap//:defs.bzl", "oci_blob_pull")

# Dummy data comes from crawling `crane manifest mirror.gcr.io/registry:latest`
# for until I got to the first layer.

# Test out by running `bzl fetch @REPO//...` then `cat $(bazel info output_base)/external/REPO`

oci_blob_pull(
    name = "test-blob",
    digest = "sha256:91dceb018e81eefd8f12f94fce01ae9ad1cbc0c941e38ff897642f97b0954e1c",
    registry = "mirror.gcr.io",
    repository = "library/registry",
)

oci_blob_pull(
    name = "test-archive",
    digest = "sha256:91dceb018e81eefd8f12f94fce01ae9ad1cbc0c941e38ff897642f97b0954e1c",
    extract = True,
    registry = "mirror.gcr.io",
    repository = "library/registry",
    type = "tar.gz",
)

oci_blob_pull(
    name = "com_github_datadog_rules_oci",
    digest = "sha256:cc6c59ed7da6bb376552461e06068f883bbe335359c122c15dce3c24e19cd8e2",
    extract = True,
    registry = "ghcr.io",
    repository = "datadog/rules_oci/rules",
    type = "tar.gz",
)

load("@com_github_datadog_rules_oci//oci:toolchain.bzl", "register_compiled_oci_toolchains")
register_compiled_oci_toolchains(name = "oci_toolchain")

